"""Endpoint-conditioned compositional decoding (fresh bounded probe).

Endpoint lexical choices are paired *before* interiors are expanded.  Each
pair exposes a character equation at both ends; the middle constituents are
then selected from ordinary, independently authored alternatives.  Nothing
is generated by reversing a completed string.
"""
from __future__ import annotations
import hashlib, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "runs/endpoint-conditioned-compositional-decoder-20260920.json"

LEFT_ENDPOINTS = {
    "a": ("a careful botanist", "a patient cartographer"),
    "t": ("the quiet librarian", "the young violinist"),
}
RIGHT_ENDPOINTS = {
    "a": ("near a quiet harbor", "beside a small veranda"),
    "t": ("before the last train", "under the silent moon"),
}
LEFT_INTERIORS = ("records local birds", "sketches distant hills", "carries fresh maps")
RIGHT_INTERIORS = ("answers a folded letter", "opens the wooden gate", "marks an old trail")

def norm(s: str) -> str:
    return re.sub(r"[^a-z]", "", s.casefold())

def audit(s: str) -> dict:
    t = norm(s)
    mismatch = next(((i, t[i], t[-1-i]) for i in range(len(t)//2) if t[i] != t[-1-i]), None)
    f = hashlib.sha256(t.encode()).hexdigest()
    rv = hashlib.sha256(t[::-1].encode()).hexdigest()
    return {"letters": len(t), "exact": bool(t) and mismatch is None,
            "first_mismatch": mismatch, "sha256_forward": f,
            "sha256_reverse": rv, "sha_equal": f == rv}

def run() -> dict:
    rows, endpoint_pairs = [], []
    # Jointly choose compatible lexical endpoints, then expand interiors.
    for key, lefts in LEFT_ENDPOINTS.items():
        for right in RIGHT_ENDPOINTS[key]:
            endpoint_pairs.append((key, lefts, right))
            for left in lefts:
                for li in LEFT_INTERIORS:
                    for ri in RIGHT_INTERIORS:
                        text = f"{left} {li}; {ri} {right}."
                        rows.append({"rendered": text, "endpoint_key": key,
                            "left_endpoint": left, "right_endpoint": right,
                            "interior_left": li, "interior_right": ri,
                            "endpoint_equation": {
                                "left_first": norm(left)[0],
                                "reverse_right_last": norm(right)[-1],
                                "matched": norm(left)[0] == norm(right)[-1]},
                            "audit": audit(text),
                            "provenance": {"left_endpoint": "fresh authored lexical choice",
                                "right_endpoint": "fresh authored lexical choice",
                                "interiors": "fresh disjoint ordinary clause alternatives",
                                "endpoint_before_interior": True,
                                "finished_tape_reversal": False, "post_hoc_repair": False,
                                "catalogue_text": False, "mirrored_units": False,
                                "repeated_units": False}})
    rows.sort(key=lambda r: -r["audit"]["letters"])
    exact = [r for r in rows if r["audit"]["exact"] and r["audit"]["letters"] > 38]
    controls = [{"rendered": "The gardener waters young roses.", "audit": audit("The gardener waters young roses.")},
                {"rendered": "A calm teacher reads beside the window.", "audit": audit("A calm teacher reads beside the window.")}]
    return {"experiment_id": "endpoint-conditioned-compositional-decoder-20260920",
        "method": "joint lexical endpoint pairing followed by compositional interior expansion",
        "stats": {"endpoint_keys": len(LEFT_ENDPOINTS), "endpoint_pairs": len(endpoint_pairs),
                  "rendered_candidates": len(rows), "fresh_exact_gt38": len(exact),
                  "max_letters": max(r["audit"]["letters"] for r in rows)},
        "rendered_candidates": rows, "exact_candidates": exact, "controls": controls,
        "novelty_preflight": {"status": "passed", "signature": "joint-endpoint-pair|interior-expansion|outer-equation",
            "distinct_from": "prior endpoint filters: endpoint lexical alternatives are co-designed as paired schemas before any interior expansion",
            "finished_tape_reversal": False, "post_hoc_repair": False},
        "provenance": {"audits": ["independent two-pointer mismatch", "forward/reverse SHA-256"],
            "reader_gate": "closed unless fresh exact >38 appears",
            "next_construction": "add agreement-typed endpoint schemas (determiner+noun and preposition+noun) while retaining joint outer pairing; hold out every interior bank used here"},
        "status": "fresh exact >38 candidate requires human reading" if exact else "no fresh exact >38 candidate"}

if __name__ == "__main__":
    result = run(); OUT.parent.mkdir(exist_ok=True); OUT.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result["stats"]))
