"""Mirror-pairs generated by walking the space, not harvested from the record.

A mirror-pair is a short palindrome whose mirror point lands exactly on a word
boundary, so it falls into two halves that spell each other backwards and can
be read as two separate sentences. Nesting k of them around a centre gives a
palindrome of any length whose second half is text the reader has not seen —
which is the only construction in this repository that is both letter-level and
long. See docs/NORTH-STAR.md for why the alternatives do not count.

The units this project shipped until now came out of a catalogue. These come
out of a walk over the vocabulary, which means they are ours, and it also means
there is no shortage: the space of 20-30 letter palindromes is large enough
that the binding constraint is choosing, not finding.

Two things the earlier hunt got wrong, both of them about WHERE the walk
spends its budget:

- A depth-first walk under a time budget drills one corner. `runs/` holds
  84,059 filtered pairs of which most open "no it call..." — one mirror core
  spawning thousands of near-identical siblings. Sharding on the opening unit
  and taking a small node budget per shard trades depth for breadth, which is
  the right trade when every shard holds more than the budget can exhaust.
- A pair is TWO clauses, and its families are keyed by the junction — the last
  word of the left half and the first word of the right — because that is the
  mirror core the siblings share. Capping there is what stops "attention"
  returning forty times.
"""
from __future__ import annotations

import time
from collections import Counter
from typing import Callable, Iterator, Optional, Sequence

from .exhaustive import enumerate_palindromes, hunt_vocabulary
from .lexicon import is_real_word
from .search import WordTries

Pair = tuple[list[str], list[str]]


def split_at_mirror(words: Sequence[str]) -> Optional[Pair]:
    """The two halves, when the mirror point falls between two words.

    Returns None when it falls inside one — those are centres, not pairs, and
    a centre cannot carry the construction because it is a palindrome on its
    own (criterion 3 allows exactly one of those in a paragraph).
    """
    total = sum(len(w) for w in words)
    run = 0
    for i, w in enumerate(words):
        run += len(w)
        if run * 2 == total:
            return list(words[:i + 1]), list(words[i + 1:])
        if run * 2 > total:
            return None
    return None


def pair_vocabulary(words: Sequence[str], zipf: Callable[[str], float],
                    lexicon, min_zipf: float = 3.6) -> list[str]:
    """What the walk may build from.

    `hunt_vocabulary` drops filler and rare words; the dictionary test on top
    of it drops the acronyms a frequency list is full of. Without it the walk
    returns "no is ill october a" and "mug dev omega cuba", which are letter-
    valid and not English at any length.

    Single letters other than "a" and "i" are the same problem in miniature:
    perfect overhang filler, never a word.

    Contraction spellings are added back after the dictionary test rather than
    exempted from it. "dont" and "youre" are not headwords and should not be —
    what they are is the only letter string the search can place for words a
    reader sees every day, and `spelling` puts the apostrophe back on the way
    out. Without them the walk cannot build a sentence with a contraction in
    it, which rules out most of how English is actually spoken.
    """
    from .spelling import CONTRACTIONS

    kept = [w for w in hunt_vocabulary(words, zipf, min_zipf)
            if is_real_word(w, lexicon) and (len(w) > 1 or w in ("a", "i"))]
    have = set(kept)
    kept += [w for w in CONTRACTIONS
             if w not in have and zipf(w) >= min_zipf]
    return kept


def acceptable_pair(left: Sequence[str], right: Sequence[str],
                    min_words: int = 3) -> bool:
    """Structural conditions a pair must meet before anything reads it.

    A word used in both halves means the mirror is returning the reader's own
    words to them, which is the repetition criteria 4 and 5 exist to stop, one
    scale down.
    """
    if len(left) < min_words or len(right) < min_words:
        return False
    if set(left) & set(right):
        return False
    words = list(left) + list(right)
    return len(set(words)) == len(words)


def junction(left: Sequence[str], right: Sequence[str]) -> tuple:
    """The family key: the words either side of the mirror point.

    Siblings differ in their openings and agree here, because the mirror core
    is what generated them.
    """
    return (left[-1], right[0])


def hunt(tries: WordTries, *, shards: int = 600, node_budget: int = 60000,
         min_letters: int = 20, max_letters: int = 30, max_overhang: int = 16,
         max_units: int = 10, min_words: int = 3, per_family: int = 3,
         deadline: Optional[float] = None,
         shard_indices: Optional[Sequence[int]] = None,
         allow_join=None, join_slack: int = 0) -> Iterator[Pair]:
    """Walk shard by shard, yielding pairs, capped per family.

    Breadth first across shards rather than depth within one: each shard gets
    `node_budget` nodes and the next one starts somewhere else in the space.
    `shard_indices` names which shards this caller owns, which is how the walk
    splits across processes without two of them covering the same subtree.

    Shards are cut on the opening unit, so `shards` above the vocabulary size
    is not a waste and not a bug: it gives one opening per shard, which is the
    finest split there is, and the budget then applies per opening. Coverage
    stays complete either way — the openings partition the space.
    """
    seen: Counter = Counter()
    emitted: set[tuple[str, str]] = set()
    for shard in (range(shards) if shard_indices is None else shard_indices):
        if deadline is not None and time.time() > deadline:
            return
        for units in enumerate_palindromes(
                tries, max_letters=max_letters, min_letters=min_letters,
                max_overhang=max_overhang, max_units=max_units,
                shard=shard, shards=shards, node_budget=node_budget,
                shuffle_seed=shard, allow_join=allow_join,
                join_slack=join_slack):
            words = [w for u in units for w in u.split()]
            split = split_at_mirror(words)
            if split is None:
                continue
            left, right = split
            if not acceptable_pair(left, right, min_words=min_words):
                continue
            key = (" ".join(left), " ".join(right))
            if key in emitted:
                continue
            fam = junction(left, right)
            if seen[fam] >= per_family:
                continue
            seen[fam] += 1
            emitted.add(key)
            yield left, right
